spring.application.name=stock

# ? DB desde Railway
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Driver class (optional in modern Spring Boot versions)
spring.datasource.driver-class-name=org.postgresql.Driver

# logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.pattern.console=[%thread] %-5level: %logger - %msg%n

spring.main.banner-mode=off

# errores
spring.mvc.problemdetails.enabled=true
server.error.include-message=always

# jwt
jwt.secret=${JWT_SECRET}

# puerto Railway
server.port=${PORT:8080}
