spring.application.name=stock

# Conexión Manual (Usaremos estos nombres exactos en Railway)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Puerto y Logs
server.port=${PORT:8080}
spring.jpa.show-sql=true
logging.level.root=INFO

# JWT
jwt.secret=${JWT_SECRET}

